import Card from "./Card/Card";
import Paragraph from "./Paragraph/Paragraph";
import Divider from "./Divider/Divider";
import Button from "./Button/Button";
import InputText from "./InputText/InputText";
import Clock from "./Clock/Clock";
import Logo from "./Logo/Logo";
import Profil from "./Profil/Profil";
import Title from "./Title/Title";
import Section from "./Section/Section";
import Genre from "./Genre/Genre";
import Image from "./Image/Image";
export {Card, Paragraph, Divider, Button, InputText, Clock, Logo, Profil, Title, Section, Genre, Image};