import Menu from "./Menu/Menu";
import GroupCard from "./GroupCard/GroupCard";
import AlaUne from "./AlaUne/AlaUne";
import Authentification from "./Authentification/Authentification";
import Register from "./Register/Register";
import InfoGame from "./InfoGame/InfoGame";
import Comments from "./Comments/Comments";
import PlusInfoGame from "./PlusInfoGame/PlusInfoGame";
import GroupCardCateg from './GroupCardCateg/GroupCardCateg';
import GroupCardGame from "./GroupCardGame/GroupCardGame";
export { Menu , GroupCard, AlaUne, Authentification, Register, PlusInfoGame, InfoGame, Comments, GroupCardCateg, GroupCardGame};